### ISSUE TITLE
Stuck after parsing template file

### ISSUE THREAD

**Issue by JuanCarbo** [pdevito3/craftsman#15] opened 2021-02-25 15:00 UTC
The script stops after displaying the message 

>Your template file was parsed successfully.

The script creates a solution in a sub-folder, but it doesn't have any entities or swagger in it.

### Steps to reproduce

- Create a new yaml file with the CarbonKitchen.Api template
- Open a new powershell window in the file's directory
- Run ./ApiTemplateName.yaml

### Further technical details

Craftsman version (`dotnet tool list -g`): 0.8.1

- Checked that the console wasn't on select mode so it wasn't stopped by that
- Tried running it several times.
- Once I left it running for a few hours.

###Yaml file used
[ApiTemplateName.zip](https://github.com/pdevito3/craftsman/files/6043804/ApiTemplateName.zip)

**Comment by pdevito3** [comment] 2021-02-25 15:03
so to confirm, your doing `craftsman new:api ./ApiTemplateName.yaml`? 

Can you try it with a non-relative path? I think that's probably the issue (if so, will bug and either add in compatibility or an error message around it)

**Comment by pdevito3** [comment] 2021-02-25 15:09
Hmm, i just tried it myself as well and am seeing the issue. I'll dig a bit and get back to you. Thanks for letting me know

**Comment by sgebhardt** [comment] 2021-02-25 16:13
I had the same problem a few minutes ago.

I get it fixed by (re-)installing the foundation template. 
```
dotnet new -i foundation.api
```

Found the solution there: https://github.com/pdevito3/craftsman/issues/4#issuecomment-744701211

**Comment by pdevito3** [comment] 2021-02-25 16:17
you're using v0.8.1 as well @sgebhardt? this version of craftsman doesn't use foundation at all, so that shouldn't come into play. interesting note though. definitely curious what version you're using (`dotnet tool list -g`)

**Comment by sgebhardt** [comment] 2021-02-25 16:34
I installed craftman yesterday evening.
```
dotnet tool list -g
Package Id                Version      Commands
------------------------------------------------------
coravel-cli               0.10.0       coravel
craftsman                 0.8.1        craftsman
dotnet-ef                 3.1.7        dotnet-ef
dotnet-outdated-tool      3.0.2        dotnet-outdated
powershell                7.0.0        pwsh
```
I am using dotnet version 5.0.102.

**Comment by pdevito3** [comment] 2021-02-25 16:36
very strange but useful nonetheless. setting aside some time to look at this tonight. thanks for the insight!

**Comment by JuanCarbo** [comment] 2021-02-25 17:23
Without the relative path works like a charm on my PC. It would be a nice addition because many people use .\ to access files easily. But just an error message pointing it out would be enough I think.

**Comment by pdevito3** [comment] 2021-02-26 04:12
Hey guys, I wasn't able to reproduce this (my issue I mentioned earlier was from something else). I'm going to close this for now, but if you notice it again definitely let me know and I'll see if I can dig up something new.

@JuanCarbo, I'll make a separate ticket for the relative path handling

**Closed by pdevito3** 2021-02-26 04:12 UTC
Labels: bug

**Comment by pdevito3** [comment] 2021-02-27 03:48
It seems like this is reproducible when doing an initial craftsman install ([see here](https://github.com/pdevito3/craftsman/issues/18#issuecomment-786997240)) and **can be resolved by closing the install window and opening a new one**. This seems to be a [known sdk bug](https://github.com/dotnet/sdk/issues/8999) (craftsman is a dotnet tool).
